### ISSUE TITLE
[BUG] HMAC SHA-1 did not produce same result as before.

### ISSUE THREAD

**Issue by ngbk1993** [Waboodoo/HTTP-Shortcuts#470]
### Steps To Reproduce
1) Create a Scripting Shortcut.
2) Paste the code as below 
`const key = 'THiIsATesting';`
`const msg = [0x00, 0x00, 0x00, 0x00, 0x03, 0x51, 0x04, 0x2b];`
`const myHMAC = hmac('SHA-1', key, msg);`
`const myHMACasHex = toHexString(myHMAC);`
`showDialog(myHMACasHex);`
3) Run the script

### Expected behavior
After running the code above we should get the result printed at the DialogBox as below:
45be3f509164744c61568f3216a3cb0278c8d794

### Actual behavior
Observed different result printed at the DialogBox as below:
ad62f6e9daa831dd6ba6f8e5ff5b60a58c2e651a

### Screenshots
N/A

### Context
Please complete the following information:
- Android OS Version: 13
- App Version : 3.24.0
- Any other context about the problem that you think is relevant
1) Refer to https://github.com/Waboodoo/HTTP-Shortcuts/issues/314, i think they might be somehow related.
2) I saw there is a recent commit change on the HashActionType on the code refactor, https://github.com/Waboodoo/HTTP-Shortcuts/blob/develop/HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/scripting/actions/types/HashActionType.kt at https://github.com/Waboodoo/HTTP-Shortcuts/pull/456
3) The code was working last year (2024).

- Device ID if possible: 76DE5D4305F34380A419

**Comment by Waboodoo** [comment]
Thanks for the detailed bug report. I will include a fix for this in the next release.

**Comment by ngbk1993** [comment]
Hi @Waboodoo, thanks you so much for the quick fix.

**Comment by Waboodoo** [comment]
As of version 3.25.0, this should now be fixed

**Comment by ngbk1993** [comment]
Hi @Waboodoo, I'm able to get the latest version of 3.25.0

The code snipped below is working already
`const key = 'THiIsATesting';`
`const msg = [0x00, 0x00, 0x00, 0x00, 0x03, 0x51, 0x04, 0x2b];`
`const myHMAC = hmac('SHA-1', key, msg);`
`const myHMACasHex = toHexString(myHMAC);`
`showDialog(myHMACasHex);`

However the actual application of the code still broken, below is the scenario.
1) I have a string hex with value '000000000351042b'

2) I convert the string hex into unsigned integer byte Array

`const hexString = "000000000351042b";`
`const msg2= new Uint8Array(hexString.length / 2);`

`for (let i = 0; i < hexString.length; i += 2) {`
`    msg2[i / 2] = parseInt(hexString.substr(i, 2), 16);`
`}`

3) Perform HMAC

`const myHMACasHex2=hmac('SHA-1', key, msg2);`
`showDialog(myHMACasHex2);`

Expected Value = 45be3f509164744c61568f3216a3cb0278c8d794
Observed Value = c44471522047ddfa5c5908814ada0e870502399b

I did compared the both hardcoded **msg** array and the converted **msg2** array, they are the same. just weird that when passing into the hmac function they got different result

**Below is the code to compare 2 array**
`function arraysAreEqual(arr1, arr2) {`
`    // Check if both arrays have the same length`
`    if (arr1.length !== arr2.length) {`
`        return false;`
`    }`

`    // Compare each element of both arrays`
`    for (let i = 0; i < arr1.length; i++) {`
`        if (arr1[i] !== arr2[i]) {`
`           return false;`
`        }`
`    }`

`    // If we reach here, arrays are identical`
`    return true;`
`}`

**Workarround**
if i defined the msg2 with all 0x0 value first then the hmac able to work correctly
for instance
`const hexString = "000000000351042b";`
`const msg2= [0,0,0,0,0,0,0,0];`

`for (let i = 0; i < hexString.length; i += 2) {`
`    msg2[i / 2] = parseInt(hexString.substr(i, 2), 16);`
`}`
`const myHMACasHex2=hmac('SHA-1', key, msg2);`
`showDialog(myHMACasHex2);`

**Comment by Waboodoo** [comment]
Thanks for the detailed follow-up. I was able to reproduce and fix the issue. It seems that while your two arrays have the same content, they don't have the same type and are therefore handled differently by the JS engine. The `Uint8Array` is somehow not detected in this case, which causes the app to use the fallback strategy of force-casting it to a string, which doesn't make sense here, hence the wrong value.
I'll include the fix in the next version, though it might be few weeks before I get to releasing that.

**Comment by ngbk1993** [comment]
> Thanks for the detailed follow-up. I was able to reproduce and fix the issue. It seems that while your two arrays have the same content, they don't have the same type and are therefore handled differently by the JS engine. The `Uint8Array` is somehow not detected in this case, which causes the app to use the fallback strategy of force-casting it to a string, which doesn't make sense here, hence the wrong value. I'll include the fix in the next version, though it might be few weeks before I get to releasing that.

Hi @Waboodoo, Thanks for the fix and the detailed explanation! That makes sense. Since I have a workaround for now, it's okay if the fix is released later. Appreciate your help!
